site_name: '기초에서 AI자동화까지'
site_description: '창의력을 구성하는 힘까지.'
repo_url: 'https://github.com/carlosperate/jekyll-theme-rtd'
repo_name: 'GitHub'
docs_dir: 'docs/'
site_dir: '_site_mkdocs/'
theme: 'readthedocs'
prev_next_buttons_location: 'both'
copyright: 'Carlos Pereira Atencio'
